import type { AwsService } from '@aws-news-hub/shared';

export const AWS_SERVICES: AwsService[] = [
  'Lambda',
  'S3',
  'DynamoDB',
  'Bedrock',
  'EC2',
  'ECS',
  'CloudFront',
  'API Gateway',
  'Step Functions',
  'EventBridge',
  'SQS',
  'SNS',
  'RDS',
  'Aurora',
  'EKS',
  'IAM',
  'CloudWatch',
  'CodePipeline',
  'SageMaker',
  'Other',
];

export const SERVICE_BADGE_COLORS: Record<AwsService, { bg: string; text: string }> = {
  'Lambda': { bg: 'bg-amber-100', text: 'text-amber-800' },
  'S3': { bg: 'bg-green-100', text: 'text-green-800' },
  'DynamoDB': { bg: 'bg-blue-100', text: 'text-blue-800' },
  'Bedrock': { bg: 'bg-purple-100', text: 'text-purple-800' },
  'EC2': { bg: 'bg-orange-100', text: 'text-orange-800' },
  'ECS': { bg: 'bg-teal-100', text: 'text-teal-800' },
  'CloudFront': { bg: 'bg-indigo-100', text: 'text-indigo-800' },
  'API Gateway': { bg: 'bg-pink-100', text: 'text-pink-800' },
  'Step Functions': { bg: 'bg-rose-100', text: 'text-rose-800' },
  'EventBridge': { bg: 'bg-cyan-100', text: 'text-cyan-800' },
  'SQS': { bg: 'bg-yellow-100', text: 'text-yellow-800' },
  'SNS': { bg: 'bg-red-100', text: 'text-red-800' },
  'RDS': { bg: 'bg-sky-100', text: 'text-sky-800' },
  'Aurora': { bg: 'bg-violet-100', text: 'text-violet-800' },
  'EKS': { bg: 'bg-lime-100', text: 'text-lime-800' },
  'IAM': { bg: 'bg-slate-100', text: 'text-slate-800' },
  'CloudWatch': { bg: 'bg-emerald-100', text: 'text-emerald-800' },
  'CodePipeline': { bg: 'bg-fuchsia-100', text: 'text-fuchsia-800' },
  'SageMaker': { bg: 'bg-stone-100', text: 'text-stone-800' },
  'Other': { bg: 'bg-gray-100', text: 'text-gray-800' },
};
